### PR TITLE
Fixed to support MediaTomb

### PR DESCRIPTION
**Pull request by ribizli**
- namespace: http://schemas.xmlsoap.org/soap/envelope/
- content-type in POST

### CODE REVIEW

**Comment by mhdawson** [comment]
Can you provide a bit more context for the requested change.

**Comment by ribizli** [comment]
Mediatomb requires a content-type header for the soap message. Also the namespace was something outdated. But check the changes, it's not much.

**Comment by ribizli** [comment]
And changed the default filter value, the blackslash didn't work for me.

**Comment by ribizli** [comment]
But for now I'm using my fork (npm supports installing from github), so no push from my side.

**Comment by mhdawson** [comment]
Ok, once I get a chance I will test out with my dependent app and if all works ok merge.  Thanks for the PR.

**Comment by mhdawson** [comment]
Validated with my server and still works ok, so landing.

**Comment by mhdawson** [comment]
New version published to npm, thanks for the contribution

**Pull request merged**
